title = "Will Do"
theme = "solar-theme-hugo"
paginate = 10
pygmentsStyle = "solarized-dark" # solarized-light, -dark or -dark256
copyright = "© 2020 Will Faught"

[params]
  scheme = "preference"
  description = "Please donate to my relief fund."

[menu]
  [[menu.prof]]
    name = "GitHub"
    url = "https://github.com/willfaught"
    weight = 1
  [[menu.prof]]
    name = "LinkedIn"
    url = "https://linkedin.com/in/willfaught"
    weight = 2
  [[menu.social]]
    name = "Twitter"
    url = "https://twitter.com/willfought"
    weight = 1
  [[menu.social]]
    name = "Facebook"
    url = "https://facebook.com/will.faught"
    weight = 2
  [[menu.xmisc]]
    name = "Feed"
    url = "/index.xml"
    weight = 1
