author:
  name: Will Faught
baseurl: https://willfaught.com
copyright: © Will Faught
languagecode: en-us
enablerobotstxt: true
markup:
  goldmark:
    renderer:
      unsafe: true
  highlight:
    style: vs
menu:
  main:
  - identifier: home
    name: Home
    weight: 1
    url: /
  - identifier: blog
    name: Blog
    weight: 2
    url: /blog/
  - identifier: articles
    name: Articles
    weight: 3
    url: /articles/
  - identifier: categories
    name: Categories
    weight: 4
    url: /categories/
  - identifier: tags
    name: Tags
    weight: 5
    url: /tags/
  - identifier: search
    name: Search
    weight: 6
    url: /search/
module:
  imports:
  - path: github.com/willfaught/paige
outputs:
  home:
  - html
  - json
  - rss
paginate: 50
params:
  paigehidethemecomment: true
  paigehidethemelink: true
permalinks:
  blog: /blog/:year/:month/:day/:title/
social:
  envelope: mailto:pushes.kingdom_0e@icloud.com
  github: https://github.com/willfaught
  linkedin: https://www.linkedin.com/in/willfaught
timezone: America/Los_Angeles
title: Will Do
titlecasestyle: Go
