baseurl = "http://localhost:1313"
title = "Will Do"
theme = "hyde"

[Menus]
  main = [
      {Name = "GitHub", URL = "https://github.com/willfaught"},
      {Name = "LinkedIn", URL = "https://www.linkedin.com/in/willfaught"},
      {Name = "Twitter", URL = "https://twitter.com/willfought"},
      {Name = "Facebook", URL = "https://www.facebook.com/will.faught"},
      {Name = "Tumblr", URL = "https://willfaught.tumblr.com"}
  ]

[params]
  description = "Please donate to my relief fund."
  themeColor = "theme-base-0d"
  layoutReverse = true
