baseurl: https://willfaught.com
copyright: © Will Faught
enablerobotstxt: true
languagecode: en-us
languages:
  en:
    menu:
      main:
      - identifier: home
        name: Home
        weight: 10
        url: /
      - identifier: blog
        name: Blog
        weight: 20
        url: /blog/
      - identifier: articles
        name: Articles
        weight: 30
        url: /articles/
      - identifier: categories
        name: Categories
        weight: 40
        url: /categories/
      - identifier: tags
        name: Tags
        weight: 50
        url: /tags/
      - identifier: search
        name: Search
        weight: 60
        url: /search/
    weight: 10
markup:
  goldmark:
    renderer:
      unsafe: true
  highlight:
    noclasses: false
  tableofcontents:
    endlevel: 6
    ordered: true
    startlevel: 2
module:
  imports:
  - path: github.com/willfaught/paige
  mounts:
  # Default mounts
  - source: "archetypes"
    target: "archetypes"
  - source: "assets"
    target: "assets"
  - source: "content"
    target: "content"
  - source: "data"
    target: "data"
  - source: "i18n"
    target: "i18n"
  - source: "layouts"
    target: "layouts"
  - source: "static"
    target: "static"
  # Bootstrap
  - source: "node_modules/bootstrap/dist/css"
    target: "assets/_paige/bootstrap"
    includeFiles: ["/bootstrap.css"]
  - source: "node_modules/bootstrap/dist/js"
    target: "assets/_paige/bootstrap"
    includeFiles: ["/bootstrap.bundle.js"]
  - source: "node_modules/bootstrap/js/dist"
    target: "static/_paige/bootstrap"
  - source: "node_modules/bootstrap/scss"
    target: "assets/_paige/bootstrap"
  # Bootstrap Icons
  - source: "node_modules/bootstrap-icons/font/fonts"
    target: "static/_paige/bootstrap-icons/fonts"
  - source: "node_modules/bootstrap-icons/font"
    target: "assets/_paige/bootstrap-icons"
    includeFiles: ["/bootstrap-icons.css"]
  # Katex
  - source: "node_modules/katex/contrib/auto-render"
    target: "assets/_paige/katex"
    includeFiles: ["/auto-render.js"]
  - source: "node_modules/katex/dist/fonts"
    target: "static/_paige/katex/fonts"
  - source: "node_modules/katex/dist"
    target: "assets/_paige/katex"
    includeFiles: ["/katex.css", "/katex.js"]
outputs:
  home:
  - html
  - json
  - rss
paginate: 50
permalinks:
  articles: /:year/:month/:day/:title/
  blog: /:year/:month/:day/:title/
timezone: America/Los_Angeles
titlecasestyle: Go
