baseurl: https://willfaught.com
copyright: © Will Faught
enablerobotstxt: true
languagecode: en-us
languages:
  en:
    menu:
      main:
      - identifier: home
        name: Home
        url: /
        weight: 10
      - identifier: blog
        name: Blog
        url: /blog/
        weight: 20
      - identifier: articles
        name: Articles
        url: /articles/
        weight: 30
      - identifier: categories
        name: Categories
        url: /categories/
        weight: 40
      - identifier: tags
        name: Tags
        url: /tags/
        weight: 50
      - identifier: search
        name: Search
        url: /search/
        weight: 60
    weight: 10
markup:
  goldmark:
    renderer:
      unsafe: true
  highlight:
    noclasses: false
  tableofcontents:
    endlevel: 6
    ordered: true
    startlevel: 2
module:
  imports:
  - path: github.com/willfaught/paige
outputs:
  home:
  - html
  - json
  - rss
paginate: 50
permalinks:
  articles: /:year/:month/:day/:title/
  blog: /:year/:month/:day/:title/
timezone: America/Los_Angeles
titlecasestyle: Go
