baseurl: https://www.willfaught.com/
copyright: "&copy; Will Faught"
languagecode: en-us
markup:
  highlight:
    style: vs
paginate: 50
params:
  description: Thoughts on life, the world, and programming. Please donate to my relief fund.
  # TODO: images:
  # TODO: - foo.jpg
  title: Will Do
permalinks:
  blog: /blog/:year/:month/:day/:title/
theme: lithe
title: Will Do
