baseurl: https://www.willfaught.com
copyright: © Will Faught
languagecode: en-us
enablerobotstxt: true
markup:
  goldmark:
    renderer:
      unsafe: true
  highlight:
    style: vs
paginate: 50
params:
  description: Thoughts on technology, the world, and life.
  goimport:
    domain: willfaught.com
    modules:
    - cuckle
    - ebnf
    - gockle
    - turbine
    prefix: github.com/willfaught
    scheme: https
    type: git
  social:
  - icon: github
    link: https://github.com/willfaught
  - icon: linkedin
    link: https://www.linkedin.com/in/willfaught
permalinks:
  blog: /blog/:year/:month/:day/:title/
theme: lithe
timezone: America/Los_Angeles
title: Will Do
titlecasestyle: Go
