author:
  name: Will Faught
baseurl: https://www.willfaught.com
copyright: © Will Faught
languagecode: en-us
enablerobotstxt: true
markup:
  goldmark:
    renderer:
      unsafe: true
  highlight:
    style: vs
menu:
  main:
  - identifier: home
    name: Home
    weight: 1
    url: /
  - identifier: blog
    name: Blog
    weight: 2
    url: /blog/
  - identifier: articles
    name: Articles
    weight: 3
    url: /articles/
# - identifier: projects
#   name: Projects
#   weight: 4
#   url: /projects/
  - identifier: categories
    name: Categories
    weight: 5
    url: /categories/
  - identifier: tags
    name: Tags
    weight: 6
    url: /tags/
module:
  imports:
  - path: github.com/willfaught/paige
paginate: 50
permalinks:
  blog: /blog/:year/:month/:day/:title/
social:
  envelope: mailto:pushes.kingdom_0e@icloud.com
  github: https://github.com/willfaught
  linkedin: https://www.linkedin.com/in/willfaught
timezone: America/Los_Angeles
title: Will Do
titlecasestyle: Go
