baseurl: https://www.willfaught.com/
copyright: "&copy; Will Faught"
languagecode: en-us
enablerobotstxt: true
markup:
  goldmark:
    renderer:
      unsafe: true
  highlight:
    style: vs
paginate: 50
params:
  description: Thoughts on life, the world, and programming. Please donate to my relief fund.
permalinks:
  blog: /blog/:year/:month/:day/:title/
theme: lithe
timezone: America/Los_Angeles
title: Will Do
titlecasestyle: Go
