baseURL: "https://www.willfaught.com/"
googleAnalytics: "UA-21098218-1"
languageCode: "en-us"
paginate: 50
params:
  description: "Thoughts on life, the world, and programming. Please donate to my relief fund."
permalinks:
  blog: /blog/:year/:month/:day/:title/
theme: "lithe"
title: "Will Do"
