baseurl = "https://willfaught.com"
enablerobotstxt = true
paginate = 50
timezone = "America/Los_Angeles"
titlecasestyle = "Go"

[[cascade]]
[cascade._target]
path = "{/authors,/authors/**}"
[cascade.build]
render = "never"

[languages.en]
languagecode = "en-us"
languagedirection = "ltr"
languagename = "English"
weight = 10

[languages.en.params.paige]
copyright = "© Will Faught"
description = '<span style="display: inline-block">Thoughts on technology,</span> <span style="display: inline-block">the world, and life.</span>'
title = "Will Do"

[[languages.en.menu.main]]
identifier = "home"
name = "Home"
url = "/"
weight = 10

[[languages.en.menu.main]]
identifier = "blog"
name = "Blog"
url = "/blog/"
weight = 20

[[languages.en.menu.main]]
identifier = "articles"
name = "Articles"
url = "/articles/"
weight = 30

[[languages.en.menu.main]]
identifier = "categories"
name = "Categories"
url = "/categories/"
weight = 40

[[languages.en.menu.main]]
identifier = "tags"
name = "Tags"
url = "/tags/"
weight = 50

[[languages.en.menu.main]]
identifier = "search"
name = "Search"
url = "/search/"
weight = 60

[markup.goldmark.renderer]
unsafe = true

[markup.highlight]
noclasses = false

[markup.tableofcontents]
endlevel = 6
ordered = true
startlevel = 2

[[module.imports]]
path = "github.com/willfaught/paige"

[outputs]
home = ["atom", "html", "paige-search", "rss"]
section = ["atom", "html", "rss"]
taxonomy = ["atom", "html", "rss"]
term = ["atom", "html", "rss"]

[params.paige.list_page]
disable_authors = true
disable_date = true
disable_keywords = true
disable_reading_time = true
disable_series = true
disable_summary = true

[params.paige.page]
disable_authors = true
disable_keywords = true
disable_next = true
disable_prev = true
disable_reading_time = true
disable_series = true
disable_toc = true

[params.paige.site]
disable_breadcrumbs = true
disable_credit = true

[params.paige.feed]
page_link = "✓"

[[params.paige.feed.atom.authors]]
name = "Will Faught"

[permalinks]
articles = "/:year/:month/:day/:slug/"
blog = "/:year/:month/:day/:slug/"

[taxonomies]
author = "authors"
category = "categories"
tag = "tags"
