concurrency:
  cancel-in-progress: true
  group: "pages"
defaults:
  run:
    shell: bash
jobs:
  build-linux:
    env:
      HUGO_VERSION: 0.119.0
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Setup Hugo
        run: |
          wget -O ${{ runner.temp }}/hugo.deb https://github.com/gohugoio/hugo/releases/download/v${HUGO_VERSION}/hugo_extended_${HUGO_VERSION}_linux-amd64.deb \
          && sudo dpkg -i ${{ runner.temp }}/hugo.deb
      - name: Setup Embedded Dart Sass
        run: sudo snap install dart-sass-embedded
      - id: pages
        name: Setup Pages
        uses: actions/configure-pages@v5
      - name: Build
        run: hugo --baseURL ${{ steps.pages.outputs.base_url }} --environment production --minify
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./public
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.pages.outputs.base_url }}
    needs: build-linux
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
name: Deploy Hugo site to Pages
on:
  push:
    branches: ["**"]
  workflow_dispatch:
permissions:
  contents: read
  id-token: write
  pages: write
